# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nktk_raw.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nktk_raw.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0enktk_raw.proto\"(\n\tTrackView\x12\x0c\n\x04view\x18\x01 \x01(\x0c\x12\r\n\x05track\x18\x02 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRACKVIEW = _descriptor.Descriptor(
  name='TrackView',
  full_name='TrackView',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='view', full_name='TrackView.view', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track', full_name='TrackView.track', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['TrackView'] = _TRACKVIEW

TrackView = _reflection.GeneratedProtocolMessageType('TrackView', (_message.Message,), dict(
  DESCRIPTOR = _TRACKVIEW,
  __module__ = 'nktk_raw_pb2'
  # @@protoc_insertion_point(class_scope:TrackView)
  ))
_sym_db.RegisterMessage(TrackView)


# @@protoc_insertion_point(module_scope)
